#!/usr/bin/env php
<?php
// File: Tests/App/console

set_time_limit(0);

require_once __DIR__.'/autoload.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$input = new \Symfony\Component\Console\Input\ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'test');

$kernel = new AppKernel($env, true);
$application = new Application($kernel);
$application->run();