#!/usr/bin/env php
<?php
// File: Tests/App/console

set_time_limit(0);

require_once __DIR__.'/autoload.php';

use Smartbox\CoreBundle\Tests\AppKernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'test');

$kernel = new AppKernel($env, true);
$application = new Application($kernel);
$application->run();